### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by Violet-Vibes** [ahoyaharr/09scape-client#1]
Are you still working on this project? Thank you for what you've done so far <3

**Comment by ahoyaharr** [comment]
Hi, I haven't worked on this in a while but this code was never added to the official branch as some of it does not (and is not intended to) match the official behaviour of Jagex game client in 2009. In particular, denoising camera positions and colors and re-working the way that entities are rendered are not faithful to the original project. 

All of the deobfuscation work can be added, most of the general code cleanup and refactoring and some of the rendering optimizations could be added as well if you are interested in doing the work of going through what I've done and merging into the official branch (I guess that would be in Pazaz's repo).
